### ISSUE TITLE
xoá sinh viên, nhưng quên update size. chú ý thêm, xoá, thì phải update size ko sẽ bị lỗi

### ISSUE THREAD

**Issue by lengcheng111** [lengcheng111/java-core-basic#4]
https://github.com/lengcheng111/java-core-basic/blob/4dbba30cf07b08bcd97e76e578ec40a67a3dc7d3/src/main/java/com/oop/qlsv/QuanLySinhVien.java#L177

**Comment by daboard** [comment]
vâng em fix lại luôn ạ
